name: .NET Core

on:
  push:
    branches: [ publish ]

  pull_request:
    branches: [ publish ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --no-restore --verbosity normal

    - name: Pack
      run: dotnet pack --configuration Release --no-build --no-restore --version-suffix="beta$GITHUB_RUN_ID" ./src/ThorNet/
